dataset:
  path: cups
  camera_views: agent1_image+agent2_image+wrist_image
dp:
  shift_pad: 6
  cond_unet:
    kernel_size: 5
    use_prop: 0
  use_ddpm: 0
num_epoch: 10
epoch_len: 10000
use_ema: 1
ema_tau: 0.01
batch_size: 64
lr: 1e-4
weight_decay: 1e-6
cosine_schedule: 1
lr_warm_up_steps: 500
use_wb: 1
save_dir: exps/hydra/cups2
