dataset:
  path: data/drawer2
  camera_views: wrist_image+agent1_image+agent2_image
  predict_mode: 0
dp:
  shift_pad: 6
  cond_unet:
    kernel_size: 5
    use_prop: 1
  use_ddpm: 0
num_epoch: 5
epoch_len: 50000
use_ema: 1
ema_tau: 0.01
batch_size: 64
lr: 1e-4
weight_decay: 1e-6
cosine_schedule: 1
lr_warm_up_steps: 500
use_wb: 1
